### ISSUE TITLE
test-paths should default to "tests" not "test"

### ISSUE THREAD

**Issue by jpeak-intellify** [dbt-labs/dbt#4011] opened 2021-10-06 08:55 UTC
### Describe the bug

`dbt init` sets up the `dbt_project.yml` with some default paths.
I wanted to cleanup my `dbt_project.yml` by removing these assuming I used the default values and folder names.

Turns out the default value for `test-paths` is `test-paths: ["test"]`.
Where as the default that `dbt init` creates is `test-paths: ["tests"]`.

This seems inconsistent.

https://docs.getdbt.com/reference/project-configs/test-paths

Could the default value be:
A) Changed to look for "tests" so it matches `dbt init` OR
B) Change the default value to look for both "test" and "tests".

It is nice that `dbt init` makes these visible initially to let me know what is available.

However if I don't change these from the defaults I would like to declutter my `dbt_project.yml` and remove them and have consistent behaviour.

I haven't double checked seeds, snapshots, etc.

**Comment by jtcohen6** [comment] 2021-10-06 11:32
@jpeak-intellify Agreed!! You have great timing. We _just_ opened a PR to finally fix this, in the lead-up to v1.0: #4007

In the meantime, I'm going to close this as a dupe of the original issue (#2659)

**Closed by jtcohen6** 2021-10-06 11:32 UTC
Labels: bug, duplicate
