### ISSUE TITLE
rpc returns empty string values as null values

### ISSUE THREAD

**Issue by DylanBaker** [dbt-labs/dbt#2666] opened 2020-07-29 22:33 UTC
### Describe the bug
When using the rpc (and dbt Cloud IDE where this was discovered), values that are empty strings are being returned and displayed as null values.

### Steps To Reproduce
Using the IDE or rpc, run `select '' and fun`. The following object is returned by the rpc:
```...
        "results": [
            {
                "logs": [],
                "raw_sql": "select '' as fun\n",
                "compiled_sql": "select '' as fun\n",
...
                "table": {
                    "column_names": [
                        "FUN"
                    ],
                    "rows": [
                        [
                            null
                        ]
                    ]
                }
...
```

### Expected behavior
I would expect a response that looks like:
```
                    "rows": [
                        [
                            ""
                        ]
                    ]
```

### Screenshots and log output
If applicable, add screenshots or log output to help explain your problem.

### System information
**Which database are you using dbt with?**
- [ ] postgres
- [ ] redshift
- [ ] bigquery
- [x] snowflake
- [ ] other (specify: ____________)

**The output of `dbt --version`:**
0.16.1

**The operating system you're using:**
Mac

**Comment by davidharting** [comment] 2021-04-02 20:46
@jtcohen6 I have spent some trying to locate this bug, and was wondering if you could gut check if you think I may be on the right path.

(I am testing this against a local Postgres database, but I believe the issue is database agnostic based on what I believe to be the cause.)

I have been using `select '' as blank`, as suggested in the issue as a simplified reproduction of the bug. 

I have honed in on `dbt.core.clients.AgateHelper.table_from_rows` as what I believe to be the location of problem. 
https://github.com/fishtown-analytics/dbt/blob/ebd761e3dce2eb33bb0ccf807742c1c5f931d583/core/dbt/clients/agate_helper.py#L61

As an input, the `row` parameter contains the correct, empty string representation of the result. 

However, when we convert this into an `agate.Table` at the end of that method, that result contains a `null` instead of an empty string, and the `column_type` is `Number`.

I initially thought that our [default type tester](https://github.com/fishtown-analytics/dbt/blob/ebd761e3dce2eb33bb0ccf807742c1c5f931d583/core/dbt/clients/agate_helper.py#L38). 

```python
def build_type_tester(text_columns: Iterable[str]) -> agate.TypeTester:
    types = [
        agate.data_types.Number(null_values=('null', '')),
        agate.data_types.Date(null_values=('null', ''),
                              date_format='%Y-%m-%d'),
        agate.data_types.DateTime(null_values=('null', ''),
                                  datetime_format='%Y-%m-%d %H:%M:%S'),
        ISODateTime(null_values=('null', '')),
        agate.data_types.Boolean(true_values=('true',),
                                 false_values=('false',),
                                 null_values=('null', '')),
        agate.data_types.Text(null_values=('null', ''))
    ]
    force = {
        k: agate.data_types.Text(null_values=('null', ''))
        for k in text_columns
    }
    return agate.TypeTester(force=force, types=types)
```

We explicitly say that the empty string is a null value for the number type (in addition to all other types). However, I am still reproducing the bug even when I remove empty string as a `null_value` from all types in the default type tester.

That is where I am leaving the issue for now until I get time to return to it. I would like to set up some tests against `table_from_rows` but injecting `TypeTester`s in various configurations to see if I can eliminate the bug in this scenario. 

If I succeed in that though, I'm not sure what other implications there would be from altering the default type tester.

**Comment by jtcohen6** [comment] 2021-04-05 16:08
@davidharting Nice work! I think all of your instincts here are right on. `table_from_rows` is definitely where this is cropping up.

The way that agate's type tester works is, any string in the `null_values` tuple is converted to the python `None` type ([docs](https://agate.readthedocs.io/en/1.6.1/api/data_types.html#agate.data_types.base.DataType)). Then, when a `None` value is converted to JSON (e.g. using agate's [`print_json`](https://agate.readthedocs.io/en/1.3.1/api/table.html#agate.Table.print_json)), the python `None` value is converted to JSON `null`.

The mapping between python `None` and SQL/JSON `null` is generally fine. But we need to find a way—for Text-type columns _only_—to treat empty strings as empty strings, _not_ python `None`, with the goal of returning SQL/JSON `""`—while preserving the current behavior (empty string == `None`/`null`) for other data types.

Unfortunately, it seems that agate always treats empty strings as missing values—always coerced to `None`—even when (as you did) I tried removing `''` from the `null_values` tuple in the type tester. This happened regardless of whether the empty-string column was `Number` type (default inference) or manually overridden to be `Text` type.

```python
>>> from dbt.clients.agate_helper import table_from_rows
>>> rows=[['', None]]
>>> column_names=['blank', 'null_col']
>>> tbl1 = table_from_rows(rows, column_names)
>>> tbl1.print_json()
[{"blank": null, "null_col": null}]
>>> tbl2 = table_from_rows(rows, column_names, text_only_columns=['blank'])
>>> tbl2.print_json()
[{"blank": null, "null_col": null}]
```

Ideas:
- Before passing rows into `agate.Table`, if all the values in a column are empty strings, could we try swapping those empty strings for a unicode character that indicates "empty string" (e.g. [0x200B](https://unicodemap.org/details/0x200B/index.html)), and then convert it back out at the end?
- ...
- Should chalk this up as a point in favor of ripping out agate entirely? It gets us a lot, but it also causes us nontrivial pain (e.g. https://github.com/fishtown-analytics/dbt/issues/1466, https://github.com/fishtown-analytics/dbt/issues/3160) :)

**Comment by davidharting** [comment] 2021-04-05 19:47
@jtcohen6 Thank you so much for the thorough response!

I should be able to spend a bit more time on this on Thursday or Friday. I will take a pass at the "convert empty strings to the empty string unicode character" approach, although I have no qualms with that work being eventually unnecessary when agate is itself removed :)

**Comment by drewbanin** [comment] 2021-07-01 14:53
closed via https://github.com/dbt-labs/dbt/pull/3499

**Closed by drewbanin** 2021-07-01 14:53 UTC
Labels: bug, rpc
