### ISSUE TITLE
"tuple concurrently updated" with Postgres

### ISSUE THREAD

**Issue by alderson59** [dbt-labs/dbt#3508] opened 2021-06-29 12:27 UTC
### Describe the bug

Error while creating a view in postgres
```
  deadlock detected
  DETAIL:  Process 187 waits for ShareLock on transaction 19479; blocked by process 186.
  Process 186 waits for ShareLock on transaction 19480; blocked by process 187.
  HINT:  See server log for query details.
  CONTEXT:  while updating tuple (1,11) in relation "pg_class"
```

Occassionally also throws this:
` tuple concurrently updated`

### Steps To Reproduce

Have 2 sql files under the same model - they work when only one exists. But when two exist in the same folder (model), the error above throws.

The two sql files refer to different tables within the same schema.

### Expected behavior
2 views should be created without errors

### System information
**Which database are you using dbt with?**
- [x] postgres
- [ ] redshift
- [ ] bigquery
- [ ] snowflake
- [ ] other (specify: ____________)

**The output of `dbt --version`:**
```
installed version: 0.19.1
   latest version: 0.19.2

Your version of dbt is out of date! You can find instructions for upgrading here:
https://docs.getdbt.com/docs/installation

Plugins:
  - redshift: 0.19.1
  - bigquery: 0.19.1
  - snowflake: 0.19.1
  - postgres: 0.19.1
```

**The operating system you're using:**
`Ubuntu 20.0.4`

**The output of `python --version`:**
`Python 3.8.5`

**Comment by jtcohen6** [comment] 2021-06-29 12:37
Thanks for opening @alderson59. I don't quite understand what you mean by:

> Have 2 sql files under the same model

Could you share the code for the two models in your project? Obviously scrubbed of any sensitive details.

**Comment by alderson59** [comment] 2021-06-29 16:14
It's a large table, so I try to show some of the different types of columns queried and selected.

Important to note that these queries are all working on their own - tested via the CLI, adminer, as well as via dbt (when standalone - meaning I removed one of the sql files from the directory when doing `dbt run`)

view1.sql:
```
SELECT
        id,
        TO_TIMESTAMP(CAST(date_created AS DOUBLE PRECISION)) AS date_created,
        status,
        some_json::jsonb->>'receipt' AS receipt,
        TO_TIMESTAMP(CAST(some_json1::jsonb->>'due_by' AS DOUBLE PRECISION)) AS due_by
FROM some_schema.table1
```

view2.sql
```
SELECT
        id,
        CAST(amount/100 AS DOUBLE PRECISION) AS amount,
        status,
        TO_TIMESTAMP(created) AS date_created,
        some_json1::jsonb->>'message' AS message,
        CAST(amount2/100 AS DOUBLE PRECISION) AS amount2,
        failure_message,
        (some_json2::jsonb->>'some_key')::jsonb->>'some_other_key1' AS some_other_key1,
        ((some_json2::jsonb->>'some_key')::jsonb->>'some_other_key2')::jsonb->>'some_other_other_key' AS some_other_other_key
FROM some_schema.table2
```

> Have 2 sql files under the same model

Apologies, should have elaborated further. I also probably misunderstood what was meant by a "model" when I posted that. I now understand each model is its own `.sql` file

What I meant was, 2 sql files under the same folder/dir.

Directory structure:
```
models/views/view1.sql
models/views/view2.sql
```

dbt_project.yml:
```
models:
  project:
    views:
      +tags:
        - "some_tag"
      +materialized: view
      +post-hook: "GRANT SELECT ON ALL TABLES IN SCHEMA public,some_schema TO user;"
```

Ran with `dbt run --models tag:some_tag` - didn't seem to be any problems here.

**Comment by jtcohen6** [comment] 2021-07-02 15:20
@alderson59 Thanks for the details, it sounds like you've been able to run these models successfully. Are you still seeing the reported error when you `dbt run`?

**Comment by alderson59** [comment] 2021-07-02 16:56
yep, nothing has changed since I last posted this. Are you able to reproduce the issue?

**Comment by sdabhi23** [comment] 2021-07-03 07:28
I am also facing the same issue

### Describe the bug
I have 2 models which have some source tables in common. Both are materialised as views. When running dbt on 2 threads, the creation of the 2 views happens in parallel and one of the views throws this error. When I run these models one-by-one using the model selection syntax, they are running perfectly!

It might be possible that this error is not related to having common set of source tables

### Steps To Reproduce
Create 2 models whose materialization is set to view with some source tables in common. Set threads > 1 in `profiles.yml`. Do `dbt run`

It might be possible that this error is not related to having common set of source tables

### Expected behavior
The models should get created without any error

### Screenshots and log output
```
Running with dbt=0.19.1
Found 3 models, 10 tests, 0 snapshots, 0 analyses, 138 macros, 0 operations, 0 seed files, 5 sources, 0 exposures
05:42:06 | Concurrency: 2 threads (target='dev')
05:42:06 |
05:42:07 | 1 of 3 START view model schema.view1................. [RUN]
05:42:07 | 2 of 3 START view model schema.view2...................... [RUN]
05:42:08 | 2 of 3 ERROR creating view model schema.view2............. [ERROR in 1.15s]
05:42:08 | 3 of 3 START incremental model schema.incremental1...... [RUN]
05:42:08 | 1 of 3 OK created view model schema.view1............ [CREATE VIEW in 1.25s]
05:42:17 | 3 of 3 OK created incremental model schema.incremental1. [INSERT 0 34 in 2.61s]
05:42:17 |
05:42:17 | Finished running 2 view models, 1 incremental model in 5.98s.
Completed with 1 error and 0 warnings:
Database Error in model order_details (models/view2.sql)
  deadlock detected
  DETAIL:  Process 18470 waits for ShareLock on transaction 3317019832; blocked by process 18471.
  Process 18471 waits for ShareLock on transaction 3317019829; blocked by process 18470.
  HINT:  See server log for query details.
  CONTEXT:  while updating tuple (42,19) in relation "pg_class"
  compiled SQL at target/run/test/models/view2.sql
Done. PASS=2 WARN=0 ERROR=1 SKIP=0 TOTAL=3
```

### System information
**Which database are you using dbt with?**
- [x] postgres
- [ ] redshift
- [ ] bigquery
- [ ] snowflake
- [ ] other (specify: ____________)


**The output of `dbt --version`:**
```
installed version: 0.19.1
   latest version: 0.19.2

Your version of dbt is out of date! You can find instructions for upgrading here:
https://docs.getdbt.com/docs/installation

Plugins:
  - postgres: 0.19.1
  - redshift: 0.19.1
  - bigquery: 0.19.1
  - snowflake: 0.19.1
```

**The operating system you're using:**
Ubuntu 18.04

**The output of `python --version`:**
Python 3.6.9

### Additional context
Add any other context about the problem here.

**Comment by alderson59** [comment] 2021-07-04 06:45
> It might be possible that this error is not related to having common set of source tables

To chime in on this, I am in fact using two separate tables, but both from the same schema in the same db.

>When running dbt on 2 threads, the creation of the 2 views happens in parallel and one of the views throws this error. When I run these models one-by-one using the model selection syntax, they are running perfectly!

Spot on! When running 2 at once, one of the views get created, while the other doesn't due to the lock.

DAG flow-wise, the 2 models should be running concurrently side-by-side, which probably means dbt/postgres has trouble reading two queries at once.

Can we bump this to a higher priority? Thanks.

**Comment by alderson59** [comment] 2021-07-04 06:59
Ok, I hacked this a little, and it's a temporary fix as I think there may be some other underlying issues here.

So, knowing that two independent models can't run concurrently from the same db, I made the second one as a downstream of the first, and to do that, we need to use the `{{ref('view1')}}` function without actually parsing the SQL - so, I commented the line via SQL as such `-- {{ref('view1')}}`. Now it works, but it runs downstream of the first.

**Comment by sdabhi23** [comment] 2021-07-04 07:38
In this case you lose the parallelism of running on multiple threads ☹️ A simpler solution would be to run the views one-by-one if you con't have many views or switching to single threaded execution.

I would like to add that this only happens when 2 views are running in parallel. Not when a table and a view are running in parallel.

**Comment by alderson59** [comment] 2021-07-07 10:18
Bump on this issue, please :)

The hack I'm using above is causing me to have to write a bunch of dependencies in each model in my web of views, sadly. Lots of unnecessary debugging to ensure that it works as it should have, whether with or without concurrency.

**Comment by jtcohen6** [comment] 2021-07-07 16:43
@alderson59 @sdabhi23 I'm looking into this issue, but I haven't been able to reproduce it myself. I'd like to gather some more information, if possible:
- Could you each share the version of Postgres you're using?
- Could you each share (from `logs/dbt.log`) the exact SQL that dbt runs right before Postgres returns `deadlock detected`/`tuple concurrently updated`? My guess is that this happens when it tries to either rename or drop the existing version of the view.

**Comment by sdabhi23** [comment] 2021-07-08 05:25
* Postgres version: 11.10
* `logs/dbt.log`: I have post hooks running which grant permissions on all objects to various roles. Those are the last SQL statements running on either of the threads. Looks like I should have done permissions on the object being created instead of all objects

**Comment by jtcohen6** [comment] 2021-07-09 13:40
Aha! This sounds promising, and closer to a [known quantity](https://www.postgresql.org/message-id/CAFoTioX5gRjxf927ysQTRarP0rQOk4Wkp1exAtLDiqMK0Pg2jw%40mail.gmail.com). We recommend that post-hook grants be specific to the model just created, and grants on all objects be executed from `on-run-end` hooks instead.

What happens if you change the post-hook grant to be specific to `{{ this }}`?

**Comment by alderson59** [comment] 2021-07-12 01:05
@jtcohen6 thanks for looking into this!

Just like @sdabhi23 , I also have post hooks running grant perms. I set this in `dbt_project.yml` to the tune of:
`GRANT SELECT ON ALL TABLES IN SCHEMA public,schema1,schema2 TO user;` since the view models reference data from different schemas. This needs to be rebuilt on each run with our use case.

I'm not sure if `{{ this }}` nor `{{ this.schema }}` would do any good here.

**Comment by jtcohen6** [comment] 2021-07-12 23:12
It seems we've found the culprit: **concurrent grants on the same objects**.

@alderson59 It sounds like your approach may want to be:
- Once at the start of a run, grant `select` on all source schemas to `user`
- After each model runs, grant `select` on just that model to `user`

In practice, that could look like:
```yml
# dbt_project.yml

on-run-start:
  - "grant select on all tables in schema public, schema1, schema2 to user"

models:
  +post_hook: "grant select on {{ this }} to user"
```

I'm going to close this issue—I don't believe we need to make any code changes in dbt.

### just for fun

You could get even fancier with the all-sources grant, and write a macro that derives the set of source schemas from [`graph.sources`](https://docs.getdbt.com/reference/dbt-jinja-functions/graph) instead of specifying `public, schema1, schema2` explicitly.

```sql
-- macros/grants.sql

{% macro grant_select_on_all_tables_in_source_schemas() %}

  {% if execute %}
    {% set all_source_schemas = graph.sources.values() | map(attribute = 'schema') | list | unique %}
  {% else %}
    {% set all_source_schemas = [] %}
  {% endif %}
  
  grant select on all tables in schema {{ all_source_schemas|join(', ') }} to user
      
{% endmacro %}
```
```yml
# dbt_project.yml

on-run-start:
  - "{{ grant_select_on_all_tables_in_source_schemas() }}"
```

**Closed by jtcohen6** 2021-07-12 23:12 UTC
Labels: bug, redshift/pg

**Comment by sdabhi23** [comment] 2021-07-13 03:28
@jtcohen6 I agree that issue is with concurrent grants. But do you have any idea why this behaviour is flaky?

I mean sometimes it fails sometimes it doesn't. That's the behaviour I have observed. It only failed when those 2 particular views were running concurrently.

I will definitely switch to model specific grants, but just a thought

**Comment by jtcohen6** [comment] 2021-07-14 03:55
@sdabhi23 My sense is, those two `grant` statements need to be running concurrently to hit this error. I imagine the view models and grant statements each take <1s to execute. The error will raise only when the queries overlap, which may not be in every invocation.

**Comment by alderson59** [comment] 2021-07-16 06:53
Thanks, this fixes the issue and works like a charm 👍🏻 

@jtcohen6 , decided to try out your fun script 😃 sadly, it didn't work, and the macro returned nothing in the `graph.sources` schemas. Any hints as to why? Doesn't this automatically parse on each run? (according to what I read from the docs)

What's a good way to debug this sort of error in general? Nothing on the logs (everything ran successfully). I've been testing it by outputting just the macro text into a view to select the text. Didn't return any schema, unfortunately.
