### ISSUE TITLE
[DBT TEST] dbt test does not seems to pick the tests when +enabled is false on project level and +enabled is true on sub-model-dir level

### ISSUE THREAD

**Issue by karthikeyan-sivabaskaran** [dbt-labs/dbt#3591] opened 2021-07-17 02:46 UTC
### Describe the bug
I tried to run dbt test with the `+enabled` config turned `OFF` on **dbt project** level and the same config is turned ON at **sub-models-directory** level, and got the output `WARNING: Nothing to do. Try checking your model configs and model specification args` 

### Steps To Reproduce

`dbt init my_new_project` : to start the fresh new dbt project, which by default will have 2 models and 4 tests under example models directory.

`dbt compile`: you should see 2 models and 4 tests

Changed the dbt_project.yml file to add the +enabled config on project and model level.

```
models:
  my_new_project:
      # Applies to all files under models/example/
      +enabled: false
      example:
        +enabled: true
        materialized: view
```

After saving the dbt_project.yml file, run `dbt compile`, now you will be seeing only **2 models and 0 tests**

### Expected behavior
As per docs, configuration on model level takes higher precedence than the config declared on project level. But, this holds true for models and it seems it is not same for tests.

`dbt compile` or `dbt test` after adding the +enabled config should have picked the 4 tests which is defined in `schema.yml` file under example model directory.

### Screenshots and log output
![image](https://user-images.githubusercontent.com/38800871/126022811-565719ee-085c-44e8-b375-29595b70aca7.png)

### System information
**Which database are you using dbt with?** - **_Snowflake_**
- [ ] postgres
- [ ] redshift
- [ ] bigquery
- [&#10004;] **_snowflake_**
- [ ] other (specify: ____________)

**The output of `dbt --version`:**
```
installed version: 0.19.2
   latest version: 0.20.0

Your version of dbt is out of date! You can find instructions for upgrading here:
https://docs.getdbt.com/docs/installation

Plugins:
  - bigquery: 0.19.2
  - snowflake: 0.19.2
  - redshift: 0.19.2
  - postgres: 0.19.2
```

**The operating system you're using:**
Mac OSX

**The output of `python --version`:**
Python 3.9.6

**Comment by jtcohen6** [comment] 2021-07-17 16:02
@karthikeyan-sivabaskaran Thanks for opening the issue, and for including the simple reproduction case. I found the issue: These tests are winding up in the `disabled` dict in `manifest.json`. Why? In dbt v0.19.x (and older versions), tests look to the `models` block for their project-level configs. So even as the models they're disabling are targeted for re-enabling, the tests are still observing the blanket ban.

Here's the good news: v0.20.0 actually fixes this bug. Tests now get their own project-level configs (#3253), using a `test:` key, and should no longer be caught as side effects of `models` configs. (This is also why I wasn't able to reproduce this bug, when initially reported in Slack the other day.)

I'm going to close this issue, since it's resolved by upgrading to the latest version of dbt.

**Closed by jtcohen6** 2021-07-17 16:02 UTC
Labels: bug
