### ISSUE TITLE
Model sort and dist keys missing from config on 0.21.0rc1

### ISSUE THREAD

**Issue by Limess** [dbt-labs/dbt#3929] opened 2021-09-21 10:17 UTC
### Describe the bug
We're using this macro to ensure tables have sort keys on Redshift:

```
{% macro check_for_sort_key() -%}

    {%- if model['resource_type'] != 'test' -%}
      {%- set is_table=
          model['config']['materialized'] in ('table', 'incremental')
      -%}

      {%- set has_sort_key = 'sort' in model['config'].keys() -%}

      {% if is_table and not(has_sort_key) %}
          {{ exceptions.raise_compiler_error(model['name'] ~ " is materialized as a table, but doesn't have a sort key") }}
      {% endif %}
    {%- endif -%}

    select 1 as test;

{%- endmacro %}
```

configured using:

```
    +pre-hook:
      - "{{ signal_dbt.check_for_sort_key() }}"
```

upon upgrading from `0.21.0b1` to `0.21.0rc1` we observed this failing, with `model['config']['materialized'] in ('table', 'incremental')` returning true for the following model:

```jinja
{{
  config(
    dist="salesforce_id",
    sort=["salesforce_id", "created_at"],
    materialized="view"
  )
}}

{%- set salesforce_cases = ref('stg_sf_cases') -%}

WITH cases as (
  SELECT
    *
  FROM {{ salesforce_cases }}
)

SELECT * FROM cases
```

which is configured as a view.

I haven't looked further into this issue, e.g. what materialization dbt thinks this model is, as the priority was to rollback and raise an issue.

### Expected behavior
The model is still treated as a view

### Screenshots and log output
If applicable, add screenshots or log output to help explain your problem.

```
Unable to do partial parsing because target/partial_parse.msgpack not found
Encountered an error:
Compilation Error in model current_sf_cases (models/marts/commercial/current_sf_cases.sql)
  current_sf_cases is materialized as a table, but doesn't have a sort key
  
  > in macro check_for_sort_key (macros/check_for_sort_key.sql)
  > called by model current_sf_cases (models/marts/commercial/current_sf_cases.sql)


Exited with code exit status 2
```

### System information
**Which database are you using dbt with?**
- [ ] postgres
- [x] redshift
- [ ] bigquery
- [ ] snowflake
- [ ] other (specify: ____________)

**The output of `dbt --version`:**
```
0.21.0rc1
```

**The operating system you're using:**

Docker: `cimg/python:3.9.6`, i.e. debian

**The output of `python --version`:**

`3.9.6`

**Comment by Limess** [comment] 2021-09-22 11:21
So I can reproduce this easily locally and it seems like `sort` and `dist` keys are missing from the `config` property (ignore the model name, this just happens to be the first model this now occurs on locally):

The `report_social_engagement_counts` has the following config:
```
{{
  config(
    materialized='table',
    sort=["run_date"],
  )
}}
```

This logging statement in the `check_for_sort_key`:

```
{% do log(model['name'] ~ ": config sort " ~ model['config'], info = true) %}
```

produces:

```
report_social_engagement_counts: config: {'enabled': True, 'tags': ['nightly'], 'meta': {}, 'materialized': 'table', 'persist_docs': {'relations': True, 'columns': True}, 'quoting': {}, 'column_types': {}, 'on_schema_change': 'ignore', 'bind': False, 'post-hook': [{'sql': '{{ logging.log_model_end_event() }}', 'transaction': True}, {'sql': '{{ signal_dbt.test_late_binding_view_in_dev() }}', 'transaction': True}], 'pre-hook': [{'sql': '{{ logging.log_model_start_event() }}', 'transaction': True}, {'sql': '{{ signal_dbt.check_for_sort_key() }}', 'transaction': True}]}
```

**Comment by jtcohen6** [comment] 2021-09-22 12:15
Weird!! Here's the config I'm see at execute time (i.e. right as the model is running), with the additional log line you included above:
```
report_social_engagement_counts: config {'enabled': True, 'tags': [], 'meta': {}, 'materialized': 'table', 'persist_docs': {}, 'quoting': {}, 'column_types': {}, 'on_schema_change': 'ignore', 'dist': 'run_date', 'sort': ['run_date'], 'post-hook': [], 'pre-hook': [{'sql': '{{ check_for_sort_key() }}', 'transaction': True}]}
```

**Comment by Limess** [comment] 2021-09-28 14:45
I just checked this on v0.21.0rc2 and the same issue persists (I expected as much as the issue hasn't been identified but thought it best to confirm)

**Comment by jtcohen6** [comment] 2021-09-28 14:55
@Limess Thanks for the keeping on top of this. Short of asking for your entire project, are there any other details that could imagine being relevant here? A local override of the `config` builtin macro?

Otherwise, I can recommend alternative mechanisms to achieve the same behavior, which is to raise an `on-run-start` warning by introspecting `graph.nodes` when `execute` is true. Could you try disabling the macro, parsing your project with v0.21.0rc2, opening `manifest.json`, and seeing whether your models with sort keys defined do indeed have `sort` in their `config` objects?

**Comment by Limess** [comment] 2021-09-28 15:34
No we definitely don't override `config`.

I'll do both of the above and get back to you.

**Comment by jtcohen6** [comment] 2021-09-28 15:59
Thanks for the quick report back!

Could you give this a try? Similar idea, different point of entry:
```sql
{% macro check_for_sort_key() -%}

    {%- for node in graph.nodes.values() -%}
      {%- set is_table=
          (node['resource_type'] == 'model' and node['config']['materialized'] in ('table', 'incremental'))
      -%}

      {%- set has_sort_key = 'sort' in node['config'].keys() -%}

      {% if is_table and not(has_sort_key) %}
          {{ exceptions.raise_compiler_error(node['name'] ~ " is materialized as a table, but doesn't have a sort key") }}
      {% endif %}
    {%- endfor -%}

{%- endmacro %}
```
```yml
# dbt_project.yml
on-run-end:
  - "{{ check_for_sort_key() if execute }}"
```

**Comment by Limess** [comment] 2021-09-28 16:28
That worked great, thanks - that's our issue worked-around then!

**Comment by jtcohen6** [comment] 2021-09-28 16:44
That's great to hear @Limess!

I'm still not sure what the root cause was here, which doesn't feel great. Given that we weren't able to reproduce the error as reported, and that we managed to find a functional workaround for your project going forward, I'm going to close this issue, and remove it as a blocker for the v0.21 final release

**Closed by jtcohen6** 2021-09-28 16:44 UTC
Labels: bug
