### ISSUE TITLE
Move dbt server (RPC) into new codebase

### ISSUE THREAD

**Issue by jtcohen6** [dbt-labs/dbt#3501] opened 2021-06-28 15:19 UTC
We're rethinking the future of the [dbt server](https://docs.getdbt.com/reference/commands/rpc), with the following goals:
- stateless
- faster to initialize
- faster multiprocessing of async requests (may require writing in a language other than python)
- requiring less overhead
- loosely coupled with specific dbt versions
- eventually, supporting a more performant event/interaction protocol in addition to / instead of JSON-RPC

To that end, we'd like to move the logic that currently defines `dbt rpc` into a new, separate codebase (proposed name: `dbt-core-api`). The new package would import `dbt-core`, but it would be distributed and versioned separately from `dbt-core`, for two main reasons:
- The server should be able to abstract over several dbt versions, and add in backwards-compatible server-only functionality
- The server should _not_ be major-version 1 at the same time as `dbt-core==1.0.0`

**Comment by kwigley** [comment] 2021-08-04 13:50
dupe of https://github.com/dbt-labs/dbt/issues/3675

**Closed by kwigley** 2021-08-04 13:50 UTC
Labels: 1.0.0, enhancement
